// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhrmjkkpaudyrhdnljdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhocm1qa2twYXVkeXJoZG5samRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDA0ODMsImV4cCI6MjA3MTUxNjQ4M30.puW_omDscwyzaqerFPIUbYRkHUifsMYDdEC7TLOpIl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});